version: "3"

services:
  go:
    build: 
      context: ./
      dockerfile: Dockerfile-dev
    environment:
      - LINE_LOGIN_ID=${LINE_LOGIN_ID}
      - LINE_LOGIN_SECRET=${LINE_LOGIN_SECRET}
      - LINE_LOGIN_REDIRECT_URL=${LINE_LOGIN_REDIRECT_URL}
    volumes:
      - ./app/:/go/src/github.com/choobot/choo-pos-backend/app/
    ports:
      - "80:80"