FROM golang:1.14

WORKDIR /go/src/github.com/choobot/choo-pos-backend/app/
RUN go get -v github.com/canthefason/go-watcher
RUN go install github.com/canthefason/go-watcher/cmd/watcher
RUN go get -v github.com/golang/mock/mockgen
COPY ./app/ ./
RUN go get -d -v -t ./...

CMD ["/bin/sh","-c","watcher"]