version: "3"

services:
  go:
    build: 
      context: ./
      dockerfile: Dockerfile-dev
    environment:
      - LINE_LOGIN_ID=${LINE_LOGIN_ID}
      - LINE_LOGIN_SECRET=${LINE_LOGIN_SECRET}
      - DATA_SOURCE_NAME=${DATA_SOURCE_NAME}
    volumes:
      - ./app/:/go/src/github.com/choobot/choo-pos-backend/app/
    ports:
      - "80:80"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql/
    ports:
      - '3306:3306'
volumes:
  mysql-data: