// Code generated by MockGen. DO NOT EDIT.
// Source: handler/session_handler.go

// Package handler is a generated GoMock package.
package handler

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo"
)

// MockSessionHandler is a mock of SessionHandler interface.
type MockSessionHandler struct {
	ctrl     *gomock.Controller
	recorder *MockSessionHandlerMockRecorder
}

// MockSessionHandlerMockRecorder is the mock recorder for MockSessionHandler.
type MockSessionHandlerMockRecorder struct {
	mock *MockSessionHandler
}

// NewMockSessionHandler creates a new mock instance.
func NewMockSessionHandler(ctrl *gomock.Controller) *MockSessionHandler {
	mock := &MockSessionHandler{ctrl: ctrl}
	mock.recorder = &MockSessionHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionHandler) EXPECT() *MockSessionHandlerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSessionHandler) Get(c echo.Context, name string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", c, name)
	ret0, _ := ret[0].(string)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockSessionHandlerMockRecorder) Get(c, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionHandler)(nil).Get), c, name)
}

// Set mocks base method.
func (m *MockSessionHandler) Set(c echo.Context, name, value string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", c, name, value)
}

// Set indicates an expected call of Set.
func (mr *MockSessionHandlerMockRecorder) Set(c, name, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockSessionHandler)(nil).Set), c, name, value)
}

// Destroy mocks base method.
func (m *MockSessionHandler) Destroy(c echo.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Destroy", c)
}

// Destroy indicates an expected call of Destroy.
func (mr *MockSessionHandlerMockRecorder) Destroy(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroy", reflect.TypeOf((*MockSessionHandler)(nil).Destroy), c)
}
